[package]
name = "easy_ssh"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.16"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
sled = "0.34.7"

[profile.release]
lto = true
opt-level = "z"
strip = "symbols"
